import Head from 'next/head'
import {BsFillMoonStarsFill} from 'react-icons/bs';
import {AiFillTwitterCircle, AiFillLinkedin, AiFillGithub } from 'react-icons/ai';
import Image from 'next/image';
import dev from '../public/dev-ed-wave.png';
import code from '../public/dev.png';
import consult from '../public/consult.png';
import devops from '../public/cloud.png';
import web1 from '../public/web1.png';
import web2 from '../public/web2.png';
import web3 from '../public/web3.png';
import web4 from '../public/web4.png';
import web5 from '../public/web5.png';
import web6 from '../public/web6.png';
import { useState } from 'react';
import axios from 'axios';

export default function Home() {

  const [darkMode, setDarkMode ] = useState(false)

  const downloadResume = () =>{
    axios.get('document/armstrong-series.docx')
    .then(response =>{
      response.blob().then(blob => {
        const url = window.URL.createObjectURL(blob);
        let link = document.createElement('a');
        link.href = url;
        link.download = 'document/armstrong-series.docx';
        link.click();

      })
    })
  }
  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Armstrong Enefe</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className='bg-white px-10 md:px-20 lg:px-40 dark:bg-gray-900'>
        <section className='min-h-screen'>
          <nav className='py-10 mb-12 flex justify-between'>
            <h1 className='text-md font-burtons dark:text-white'>portfoliobyarmstrong</h1>
            <ul className='flex items-center'>
              <li><BsFillMoonStarsFill onClick={() => setDarkMode(!darkMode)} className='cursor-ponter text-2 dark:text-white'/></li> 
              <li><a className='bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8' href='#'>Resume</a></li> 
            </ul>
          </nav>
          <div className='text-center p-10'>
            <h2 className='text-5xl py-2 text-teal-600 font-medium md:text-6xl dark:text-white'>Hi, <span>👋🏽</span></h2>
            <h3 className='text-5xl py-2 text-teal-600 font-medium md:text-6xl dark:text-white'>I'm Armstrong</h3>
            <h4 className='text-2xl py-2 md:text-3xl dark:text-white'>Your Software Engineer</h4>
            <p className='text-md py-5 leading-8 text-gray-800 md:text-xl max-w-lg mx-auto dark:text-white'>
              Build enterprise apps that scale that provides solutions to your business problem
            </p>
          </div>
          <div className='text-4xl flex justify-center gap-16 py-3 text-gray-600'>
            <a href='https://twitter.com/@Iamarmstrong__'><AiFillTwitterCircle className='cursor-pointer' /></a>
            <a href='https://www.linkedin.com/in/armstrong-enefe-4a3745191/'><AiFillLinkedin className='cursor-pointer' /></a>
            <a href='https://github.com/armstrong-series/'><AiFillGithub className='cursor-pointer' /> </a>
          </div>
          <div className='relative mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 mt-20 overflow-hidden md:h-96 md:w-96'>
            <Image src={dev} alt="image" layout='fill' objectFit='cover' />
          </div>
        </section>

        <section>
          <div>
            <h3 className='text-3xl py-1 dark:text-white'>My Services</h3>
             <p className='text-md py-2 leading-8 text-gray-800 dark:text-white'>
                I Build scalable web apps for <span className='text-teal-500'>Saas niches</span>, Restful APIs for mobile plattform.
                 I understand customer-centric softwares from developement, testing, deployment and maintenance.           
             </p>

             <p className='text-md py-2 leading-8 text-gray-80 dark:text-white'>
                I work with <span className='text-teal-500'>SOLID principle</span> and service pattern architecture for codebase to enhance scalabilty and maintenance using languages and frameworks such as Php-Laravel, ReactJs, MySQL and PostgreSQL for database        
             </p>
            
          </div>
          <div className='lg:flex gap-10'>
            <div className='text-center shadow-lg p-10 rounded-xl my-10 flex-1 dark:bg-white'>
              <Image src={code} width={120} alt="code" height={100} />
              <h3 className='text-lg font-medium pt-8 pb-2 py-4 cursor-pointer'>Backend Development</h3>
              <p className='py-2'>Writing clean code following SOLID principle and service pattern</p>
              <h6 className='font-bold'>Stacks</h6>
              <p className='text-gray-800 py-1'><span className='text-teal-500'>Php Laravel</span>: For building RestFul APIs for both mobile and web platforms with beautiful software architecture and design pattern. Version: Php 7 - 8.1 </p>
              <p className='text-gray-800 py-1'>Java Springboot: Web application, building API for mobile and web platforms</p>
              <p className='text-gray-800 py-1'>ReactJs: Javascript frontend framework for interacting with my ReestFul APIs. Understand server-side rendering (SSR) </p>
              <p className='text-gray-800 py-1'>MySQL/PostgreSQL (SQL)</p>
              <p className='text-gray-800 py-1'>Postman: Testing Restful API endpoints to ensure it works to the specific development use case</p>
            </div>
            <div className='text-center shadow-lg p-10 rounded-xl my-10 flex-1 dark:bg-white'>
              <Image src={devops} width={150} alt="code" height={160} />
              <h3 className='text-lg font-medium pt-8 pb-2 py-4 cursor-pointer'>DevOps</h3>
              <p className='py-2'>Ensuring application are deployed using standard toolset and practices. 
                </p>
              <h6 className='font-bold'>Tools</h6>
              <p className='text-gray-800 py-1'>Buddyworks/Jenkins: CI/CD pipeline for deployment</p>
              <p className='text-gray-800 py-1'>Docker: Containerizing of applications</p>
              <p className='text-gray-800 py-1'><span className='text-teal-500'>Git</span>: For version control, tracking updated code changes and also changes in deployment</p>
              <p className='text-gray-800 py-1'>Kubernetes</p>
              
            </div>
            
            <div className='text-center shadow-lg p-10 rounded-xl my-10 flex-1 dark:bg-white'>
              <Image src={consult} width={120} alt="code" height={100} />
              <h3 className='text-lg font-medium pt-8 pb-2 py-4 cursor-pointer'>Project Management</h3>
              <p className='py-2'>Giving technical and non-technical solution in terms of managing project within the SDLC cycle. Also, ensuring due deligience is taken on the scalability in terms of code structure and performance </p>
              <h4>Tools</h4>
              <p className='text-gray-800 py-1'>Xmind/LucidChart: For creating project flow-charts in the form of mind maps</p>
              <p className='text-gray-800 py-1'><span className='text-teal-500'>JIRA/Trello</span>: Onboarding tasks for team, tracking changes and creating new issues</p>
              <p className='text-gray-800 py-1'>Slack: Team collaboration tool for document sharing, chats and so much more</p>
            </div>
          </div>
        </section>

        <section>
          <div>
            <h3 className='text-3xl py-1 dark:text-white'>Portfolio</h3>
            <p className='py-2 text-md leading-8 text-gray-800 dark:text-white'>Writing clean code following SOLID principle and service pattern</p>
             
          </div>
          <div className='flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap'>
            <div className='basis-1/3 flex-1'>
              <Image src={web1} className='rounded-lg object-cover cursor-pointer' alt='web1' width={'100%'} height={'100%'} layout="responsive" />
            </div>
            <div className='basis-1/3 flex-1'>
              <Image src={web2} className='rounded-lg object-cover cursor-pointer' alt='weeb2' width={'100%'} height={'100%'} layout="responsive" />
            </div>
           
            <div className='basis-1/3 flex-1'>
              <Image src={web3} className='rounded-lg object-cover cursor-pointer' alt='web3' width={'100%'} height={'100%'} layout="responsive" />
            </div>
            <div className='basis-1/3 flex-1'>
              <Image src={web4} className='rounded-lg object-cover cursor-pointer' alt='web4' width={'100%'} height={'100%'} layout="responsive" />
            </div>
            <div className='basis-1/3 flex-1'>
              <Image src={web5} className='rounded-lg object-cover cursor-pointer' alt='web5' width={'100%'} height={'100%'} layout="responsive" />
            </div>
            <div className='basis-1/3 flex-1'>
              <Image src={web6} className='rounded-lg object-cover cursor-pointer' alt='web6' width={'100%'} height={'100%'} layout="responsive" />
            </div> 
            
          </div>
        </section>

        <section>
          <div>
           <h3 className='text-3xl py-1 dark:text-white'>Opensource</h3>
          </div>
        </section>
      </main> 
    </div>
  )
}
